name: Require Gemini AI Review

     # Purpose:
     # - Enforce that PRs have the `ai-review` label before proceeding.
     # Complements:
     # - `ai-review-labels.yml` which manages applying `ai-review`/`ai-review-requested` labels.
     # - `auto-merge-coordinator.yml` which also checks labels during coordination.
     # Note: This job is a focused, fast-fail check. Keep it, but avoid duplicating the same blocking
     # message elsewhere to reduce noise.

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-ai-review:
    name: Check for 'ai-review' label
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Gemini review label present
        id: ensure-label
        run: |
          NUMBER='${{ github.event.pull_request.number }}'
          LABELS=$(gh --repo "${{ github.repository }}" pr view "$NUMBER" --json labels --jq '[.labels[].name] | join(",")')
          echo "Labels: $LABELS"
          # Honor bypass for infra/docs-only PRs
          CSV=",$LABELS,"
          if echo "$CSV" | grep -q ',skip-rfc-check,'; then
            echo "Bypass active (skip-rfc-check present). Proceeding."
          fi
          if echo "$CSV" | grep -q ',ai-review,'; then
            echo "Gemini AI review label present."
          else
            echo "Advisory: Missing 'ai-review' label. Proceeding without blocking."
            {
              echo "## Gemini AI Review (Advisory)"
              echo "- PR: #$NUMBER"
              echo "- Status: Missing 'ai-review' label"
              echo "- Action: Optional — comment '/gemini review' to request a review"
            } >> "$GITHUB_STEP_SUMMARY"
          fi
          # Always succeed — AI review is advisory, not required
          exit 0
        env:
          GH_TOKEN: ${{ github.token }}
