name: DEPRECATED - Assign RFC Issues to Copilot

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation notice
        run: |
          echo "This workflow is deprecated."
          echo "Use 'Assign RFC Issues to Agent' instead: .github/workflows/assign-rfc-issues-to-agent.yml"
          echo "It supports custom assignees, labels, and neutral guidance comments."
          exit 1
