name: Simple Conflict Resolution Agent

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      pr_numbers:
        description: 'PR numbers to resolve conflicts for (e.g., 8,10) or "all"'
        required: true
        default: 'all'
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  resolve-conflicts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ github.token }}
        
    - name: Find conflicted PRs
      id: find-conflicts
      run: |
        echo "Scanning for conflicted pull requests..."
        
        INPUT_PRS="${{ github.event.inputs.pr_numbers || 'all' }}"
        
        if [ "$INPUT_PRS" = "all" ]; then
          CONFLICTED_PRS=$(gh pr list --state=open --json number,mergeable --jq '.[] | select(.mergeable == "CONFLICTING") | .number' | tr '\n' ',' | sed 's/,$//')
        else
          CONFLICTED_PRS="$INPUT_PRS"
        fi
        
        echo "conflicted_prs=$CONFLICTED_PRS" >> $GITHUB_OUTPUT
        
        if [ -z "$CONFLICTED_PRS" ]; then
          echo "No conflicted PRs found"
          echo "has_conflicts=false" >> $GITHUB_OUTPUT
        else
          echo "Found conflicted PRs: $CONFLICTED_PRS"
          echo "has_conflicts=true" >> $GITHUB_OUTPUT
        fi
        
      env:
        GH_TOKEN: ${{ github.token }}
        
    - name: Assign Copilot and post guidance
      if: steps.find-conflicts.outputs.has_conflicts == 'true'
      run: |
        echo "Processing conflicted PRs..."
        
        CONFLICTED_PRS="${{ steps.find-conflicts.outputs.conflicted_prs }}"
        IFS=',' read -ra PR_ARRAY <<< "$CONFLICTED_PRS"
        
        for pr_num in "${PR_ARRAY[@]}"; do
          pr_num=$(echo "$pr_num" | xargs)
          
          if [ -z "$pr_num" ]; then
            continue
          fi
          
          echo "Processing PR #$pr_num..."
          
          # Get PR details
          PR_INFO=$(gh pr view "$pr_num" --json headRefName,author --jq '{branch: .headRefName, author: .author.login}')
          BRANCH_NAME=$(echo "$PR_INFO" | jq -r '.branch')
          PR_AUTHOR=$(echo "$PR_INFO" | jq -r '.author')
          
          # Skip if not a Copilot PR
          if [[ ! "$PR_AUTHOR" == *"copilot"* ]]; then
            echo "Skipping - not a Copilot agent PR"
            continue
          fi
          
          # Assign Copilot agent
          echo "Assigning Copilot agent to PR #$pr_num..."
          gh pr edit "$pr_num" --add-assignee "Copilot" || echo "Assignment may have failed or already exists"
          
          # Post conflict resolution guidance
          gh pr comment "$pr_num" --body "Conflict Resolution Agent - AUTOMATIC CONFLICT RESOLUTION NEEDED - This PR has merge conflicts that need to be resolved. Action Required: 1. Checkout branch: git checkout $BRANCH_NAME 2. Rebase against main: git rebase main 3. Resolve merge conflicts in the conflicted files 4. Push updated branch: git push --force-with-lease 5. Mark this PR ready for review (remove draft status) - Please work directly on this existing PR to resolve conflicts. Integration Note: Recent RFC001 merge added comprehensive game engine architecture. Ensure your changes integrate with the new GameEngine state management and ECS architecture."
          
          echo "Posted guidance to PR #$pr_num"
          
        done
        
      env:
        GH_TOKEN: ${{ github.token }}