name: Open Agent Test PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GitHub App installation token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create trivial change
        run: |
          BRANCH="ci/agent-triage-test-$(date +%s)"
          echo "trigger $(date -u +%Y-%m-%dT%H:%M:%SZ)" > .github/agent-triage-test.txt
          git checkout -b "$BRANCH"
          git add .github/agent-triage-test.txt
          git commit -m "test: agent triage labeling"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
          git push -u origin "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        id: create

      - name: Open PR
        run: |
          gh pr create \
            --title "test: agent triage labeling" \
            --body "Automated PR to verify auto-labeling for agent/bot authors." \
            --head "${{ steps.create.outputs.branch }}" \
            --base main \
            --draft
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
