name: Periodic Reconcile RFC Issues (every 3 hours)

on:
  schedule:
    - cron: '30 */3 * * *'  # every 3 hours at minute 30 (UTC)
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  ping:
    name: Reconcile pipeline smoke test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List RFC docs
        id: list
        shell: bash
        run: |
          set -euo pipefail
          ls -1 docs/RFC/RFC*.md 2>/dev/null | grep -E 'docs/RFC/RFC[0-9]{3}-.+\.md' | grep -v 'docs/RFC/README.md' > rfc_list.txt || true
          echo "Found RFCs:" && cat rfc_list.txt || true
          COUNT=$(wc -l < rfc_list.txt | tr -d ' ' || echo 0)
          echo "Found ${COUNT:-0} RFC file(s)"
      - name: Echo success
        run: |
          echo "Reconcile workflow minimal job OK"
