name: Periodic Reconcile RFC Issues (every 3 hours)

on:
  schedule:
    - cron: '30 */3 * * *'  # every 3 hours at minute 30 (UTC)
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  ping:
    name: Reconcile pipeline smoke test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo success
        run: |
          echo "Reconcile workflow minimal job OK"
